#!/bin/sh /etc/rc.common

# Copyright 2020 Google LLC.
# SPDX-License-Identifier: Apache-2.0

USE_PROCD=1
START=99

cmd="/usr/bin/netbird "service" "run" "--config" "/etc/netbird/config.json" "--log-level" "info" "--log-file" "/var/log/netbird/client.log""

name=$(basename $(readlink -f $0))
pid_file="/var/run/$name.pid"
stdout_log="/tmp/netbird_$name.log"
stderr_log="/tmp/netbird_$name.err"

[ -e /etc/sysconfig/$name ] && . /etc/sysconfig/$name

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && cat /proc/$(get_pid)/stat > /dev/null 2>&1
}

start_service() {
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"

        $cmd >> "$stdout_log" 2>> "$stderr_log" &
        echo $! > "$pid_file"
        if is_running; then
            netbird up --setup-key $NETBIRD_SETUP_KEY --management-url $NETBIRD_MANAGMENT_URL
        else
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
}

stop_service() {
    if is_running; then
        echo -n "Stopping $name.."
        netbird down
        kill $(get_pid)
        for i in $(seq 1 10)
        do
            if ! is_running; then
                break
            fi
            echo -n "."
            sleep 1
        done
        echo
        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
}